### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by zerocity** [RetroShare/RetroShare#272] opened 2016-02-08 22:27 UTC
hi ,

i tried it on arch and opensuse to compile retroshare. 
It seems that the readme is outdated. 

i did :
qmake 
make 

on line 2015 ([makelog.txt](https://github.com/RetroShare/RetroShare/files/122299/makelog.txt)) the error starts.
some errors we could remove with 
`g++ -Wl,-O1 -lssl -lcrypto -ldl -lz -o RetroShare06-nogui temp/linux-g++/obj/notifytxt.o temp/linux-g++/obj/retroshare.o temp/linux-g++/obj/TerminalApiClient.o     -rdynamic ../../libretroshare/src/lib/libretroshare.a ../../libresapi/src/lib/libresapi.a`

maybe you can help :)

**Comment by YamashitaRen** [comment] 2016-02-08 23:22
Same on Debian Jessie.

edit : curiously it works on my Arch...

**Comment by stylesuxx** [comment] 2016-02-09 10:12
I had the same problem on my Debian Sid notebook. Interestingly it compiled fine on my Debian Sid desktop. All the same packages are installed in the exact same version -_-

**Comment by TheSentry** [comment] 2016-02-09 12:09
I once had this problem and the cause was a different gcc version. Are those the same, too?

**Comment by electron128** [comment] 2016-02-09 18:35
The command on line 2015 is missing a lot of libraries. The libraries are specified in the .pro files. Did qmake print a warning about missing libraries?

It looks like dependencies of libretroshare are specified in libretroshare.pro, and retroshare-gui and retroshare-nogui inherit these dependencies.
See https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/libretroshare.pro#L165

Does pkg-config work?

**Comment by YamashitaRen** [comment] 2016-02-09 19:02
qmake didn't print anything.
pkg-config works
`$ pkg-config --modversion gnome-keyring-1 libssl libupnp libcrypto zlib
3.12.0
1.0.1k
1.6.19+git20141001
1.0.1k
1.2.8`

**Comment by G10h4ck** [comment] 2017-06-02 10:04
This bug should be already fixed in master branch, feel free to reopen if it's not the case

**Closed as completed by G10h4ck** 2017-06-02 10:04 UTC
Labels: bug
