### ISSUE TITLE
undefined reference to bunch of libmicrohhtpd related objects

### ISSUE THREAD

**Issue by bvk-ch** [RetroShare/RetroShare#834] opened 2017-05-22 05:39 UTC
Hello;
I even build and install libmicrphttpd ver=0.9.54 but I get this errors:
```
_RsSyntaxHighlighter.o temp/linux-g++/obj/moc_idle.o temp/linux-g++/obj/moc_IdDialog.o temp/linux-g++/obj/moc_IdEditDialog.o temp/linux-g++/obj/moc_IdDetailsDialog.o temp/linux-g++/obj/moc_CirclesDialog.o temp/linux-g++/obj/moc_CreateCircleDialog.o temp/linux-g++/obj/moc_PeopleDialog.o temp/linux-g++/obj/moc_CircleWidget.o temp/linux-g++/obj/moc_IdentityWidget.o temp/linux-g++/obj/moc_GxsForumsDialog.o temp/linux-g++/obj/moc_GxsForumGroupDialog.o temp/linux-g++/obj/moc_CreateGxsForumMsg.o temp/linux-g++/obj/moc_GxsForumThreadWidget.o temp/linux-g++/obj/moc_GxsForumsFillThread.o temp/linux-g++/obj/moc_GxsForumUserNotify.o temp/linux-g++/obj/moc_GxsForumGroupItem.o temp/linux-g++/obj/moc_GxsForumMsgItem.o temp/linux-g++/obj/moc_GxsChannelDialog.o temp/linux-g++/obj/moc_GxsChannelGroupDialog.o temp/linux-g++/obj/moc_CreateGxsChannelMsg.o temp/linux-g++/obj/moc_GxsChannelPostsWidget.o temp/linux-g++/obj/moc_GxsChannelFilesWidget.o temp/linux-g++/obj/moc_GxsChannelFilesStatusWidget.o temp/linux-g++/obj/moc_GxsChannelGroupItem.o temp/linux-g++/obj/moc_GxsChannelPostItem.o temp/linux-g++/obj/moc_GxsChannelUserNotify.o temp/linux-g++/obj/moc_PostedDialog.o temp/linux-g++/obj/moc_PostedListWidget.o temp/linux-g++/obj/moc_PostedItem.o temp/linux-g++/obj/moc_PostedGroupDialog.o temp/linux-g++/obj/moc_PostedGroupItem.o temp/linux-g++/obj/moc_PostedCreatePostDialog.o temp/linux-g++/obj/moc_PostedUserNotify.o temp/linux-g++/obj/moc_GxsGroupDialog.o temp/linux-g++/obj/moc_GxsIdDetails.o temp/linux-g++/obj/moc_GxsIdChooser.o temp/linux-g++/obj/moc_GxsIdLabel.o temp/linux-g++/obj/moc_GxsCircleChooser.o temp/linux-g++/obj/moc_GxsCircleLabel.o temp/linux-g++/obj/moc_GxsIdTreeWidgetItem.o temp/linux-g++/obj/moc_GxsCommentTreeWidget.o temp/linux-g++/obj/moc_GxsCommentContainer.o temp/linux-g++/obj/moc_GxsCommentDialog.o temp/linux-g++/obj/moc_GxsCreateCommentDialog.o temp/linux-g++/obj/moc_GxsGroupFrameDialog.o temp/linux-g++/obj/moc_GxsMessageFrameWidget.o temp/linux-g++/obj/moc_GxsMessageFramePostWidget.o temp/linux-g++/obj/moc_GxsGroupFeedItem.o temp/linux-g++/obj/moc_GxsFeedItem.o temp/linux-g++/obj/moc_RsGxsUpdateBroadcastBase.o temp/linux-g++/obj/moc_RsGxsUpdateBroadcastWidget.o temp/linux-g++/obj/moc_RsGxsUpdateBroadcastPage.o temp/linux-g++/obj/moc_GxsGroupShareKey.o temp/linux-g++/obj/moc_GxsUserNotify.o temp/linux-g++/obj/moc_GxsFeedWidget.o temp/linux-g++/obj/moc_TokenQueue.o temp/linux-g++/obj/moc_RsGxsUpdateBroadcast.o temp/linux-g++/obj/moc_WebuiPage.o temp/linux-g++/obj/qrc_images.o temp/linux-g++/obj/qrc_icons.o temp/linux-g++/obj/qrc_lang.o temp/linux-g++/obj/qrc_content.o temp/linux-g++/obj/qrc_emojione.o temp/linux-g++/obj/qrc_Posted_images.o    -L/usr/lib -rdynamic /home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libretroshare/src/lib/libretroshare.a ../../libbitdht/src/lib/libbitdht.a -lsqlcipher -ldl ../../openpgpsdk/src/lib/libops.a -lbz2 -lssl -pthread -lupnp -lthreadutil -lixml -lcrypto -lz /home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a -lX11 -lXss -L/usr/lib -L/usr/X11R6/lib -lQtNetwork -lQtUiTools -L/builddir/qt-everywhere-opensource-src-4.8.7/lib -lQtXml -lQtGui -lQtCore -lpthread 
/usr/lib/libsqlcipher.so: warning: warning: EVP_CipherFinal is often misused, please use EVP_CipherFinal_ex and EVP_CIPHER_CTX_cleanup
temp/linux-g++/obj/AboutWidget.o: In function `AboutWidget::on_copy_button_clicked()':
AboutWidget.cpp:(.text+0x1a0a): undefined reference to `MHD_get_version'
temp/linux-g++/obj/HelpDialog.o: In function `HelpDialog::HelpDialog(QWidget*)':
HelpDialog.cpp:(.text+0x7c8): undefined reference to `MHD_get_version'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::ApiServerMHD::start()':
ApiServerMHD.cpp:(.text+0x4a3): undefined reference to `MHD_start_daemon'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::ApiServerMHD::stop()':
ApiServerMHD.cpp:(.text+0x60e): undefined reference to `MHD_stop_daemon'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::secure_queue_response(MHD_Connection*, unsigned int, MHD_Response*)':
ApiServerMHD.cpp:(.text+0x6f6): undefined reference to `MHD_get_response_header'
ApiServerMHD.cpp:(.text+0x721): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x741): undefined reference to `MHD_get_connection_values'
ApiServerMHD.cpp:(.text+0x92d): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x93c): undefined reference to `MHD_queue_response'
ApiServerMHD.cpp:(.text+0x9b9): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text+0x9d2): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x9e2): undefined reference to `MHD_queue_response'
ApiServerMHD.cpp:(.text+0x9ea): undefined reference to `MHD_destroy_response'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::sendMessage(MHD_Connection*, unsigned int, std::string)':
ApiServerMHD.cpp:(.text+0xdea): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text+0xe03): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0xe19): undefined reference to `MHD_destroy_response'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::ApiServerMHD::accessHandlerCallback(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**)':
ApiServerMHD.cpp:(.text+0xf78): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text+0xf91): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0xfa9): undefined reference to `MHD_destroy_response'
ApiServerMHD.cpp:(.text+0x1427): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text+0x1440): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x1457): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x146f): undefined reference to `MHD_destroy_response'
ApiServerMHD.cpp:(.text+0x1813): undefined reference to `MHD_create_response_from_fd'
ApiServerMHD.cpp:(.text+0x1845): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x1872): undefined reference to `MHD_destroy_response'
ApiServerMHD.cpp:(.text+0x1fce): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text+0x1fe7): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text+0x1fff): undefined reference to `MHD_destroy_response'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::MHDFilestreamerHandler::handleRequest(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*)':
ApiServerMHD.cpp:(.text._ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x339): undefined reference to `MHD_create_response_from_callback'
ApiServerMHD.cpp:(.text._ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x404): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text._ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api22MHDFilestreamerHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x432): undefined reference to `MHD_destroy_response'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::MHDApiHandler::handleRequest(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*)':
ApiServerMHD.cpp:(.text._ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x716): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text._ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x751): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text._ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x76a): undefined reference to `MHD_destroy_response'
ApiServerMHD.cpp:(.text._ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api13MHDApiHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x910): undefined reference to `MHD_add_response_header'
/home/mnsr/Git-Dir/Retroshare/retroshare-gui/src/../../libresapi/src/lib/libresapi.a(ApiServerMHD.o): In function `resource_api::MHDUploadHandler::handleRequest(MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*)':
ApiServerMHD.cpp:(.text._ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x285): undefined reference to `MHD_create_response_from_data'
ApiServerMHD.cpp:(.text._ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x29e): undefined reference to `MHD_add_response_header'
ApiServerMHD.cpp:(.text._ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm[_ZN12resource_api16MHDUploadHandler13handleRequestEP14MHD_ConnectionPKcS4_S4_S4_Pm]+0x2b6): undefined reference to `MHD_destroy_response'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.retroshare-gui:1134: RetroShare06] Error 1
```

**Comment by G10h4ck** [comment] 2017-06-01 20:53
seems a linking problem, it probably depends on your build environment not setup properly, I close this bug for now as i cannot reproduce it

**Closed as completed by G10h4ck** 2017-06-01 20:53 UTC
