### ISSUE TITLE
HTTPS for Website

### ISSUE THREAD

**Issue by Simted** [RetroShare/RetroShare#935] opened 2017-07-08 11:44 UTC
Noticed that http://retroshare.net/ is lacking HTTPS.

Is it possible for this to be sorted?

**Comment by cavebeat** [comment] 2017-07-11 21:14
duplicate of https://github.com/RetroShare/RetroShare/issues/839

TL;DR the homepage is hosted at GitHub-Pages, which are HTTP only.

**Comment by alfinal** [comment] 2019-04-24 10:06
@cavebeat I think you forgot close it as duplicated.

**Closed** 2019-04-24 10:12 UTC
