### ISSUE TITLE
Android web-UI

### ISSUE THREAD

**Issue by inferrna** [RetroShare/RetroShare#857] opened 2017-05-30 17:08 UTC
Following instructions https://github.com/RetroShare/RetroShare/blob/master/README-Android.asciidoc
I changed line 
```CONFIG+=no_retroshare_gui CONFIG+=no_retroshare_nogui CONFIG+=no_retroshare_plugins CONFIG+=retroshare_android_service CONFIG+=libresapilocalserver CONFIG+=no_libresapihttpserver CONFIG+=no_sqlcipher CONFIG+=retroshare_qml_app```
to
```CONFIG+=no_retroshare_gui CONFIG+=no_retroshare_nogui CONFIG+=no_retroshare_plugins CONFIG+=retroshare_android_service CONFIG+=libresapilocalserver CONFIG+=libresapihttpserver CONFIG+=no_sqlcipher CONFIG+=retroshare_qml_app```
in hope to access app from android browser. But I was failure. Is there any chances to use retroshare on mobile device this way?

**Comment by G10h4ck** [comment] 2017-05-31 10:32
Yes it is possible in principle, the problem is I haven't been capable to compile successfully libmicrohttpd for android, and I haven't dedicated much time to that as it is not my main focus, but I would accept contributions in that direction, especially in form of Merge Requests.

For android stuff please refer to my fork in the branch qmlapp_pex_alpha because a bunch of fixes has been done there and will be fixed here too as soon as I prepare a pull request and it get reviewed and merged
https://github.com/G10h4ck/RetroShare/tree/qmlapp_pex_alpha

**Comment by G10h4ck** [comment] 2019-08-20 12:17
the new JSON API made the old libresapi obsolete

**Closed as completed by G10h4ck** 2019-08-20 12:17 UTC
