### ISSUE TITLE
Identity avatar broken Base64 string 

### ISSUE THREAD

**Issue by b1rdG** [RetroShare/RetroShare#1946] opened 2020-05-17 20:13 UTC
Hi,
After check for identities details using:

```bash
curl -u "location:passs" -d '{ "ids" : ["identityid"]}' http://127.0.0.1:9092/rsIdentity/getIdentitiesInfo -vv
```

I get a strange result on the Base64 avatar string:

```
            "mImage": {
                "mData": "�\u0007\u0000\\�\u0000\u0000�\u0007\u0000\\�\u0000\u0000�>\u0016\\�\u0000\u0000�>\u0016\\�\u0000\u0000CAIAAABMXPacAAAACXBIWXMAABYlAAAWJQFJUiTwAAAgAElEQVR4nHS96a9tyXUfttaqqj2c4c5vYk8kRbFDSrIkypJJNgdJAUXSkkgZhhUgCQIEQQIYMIL8AYZkIPKHIEEMRIHzIUGCGAlsI5EhJwEkijIl0aQsaiCbIrvJJtlz9+v
[...Base64 String finished with padding...]
```

The first characters seems to be Unicode characters, not included on the Base64 strings.  If I copy paste the Base64 string (without this leading Unicode characters)  in online Base64 to image service, the image can't be composed.   

It seems that the problem is on the serialization of the image on Backend code, but I'm not sure of how to fix this.

**Comment by sehraf** [comment] 2020-05-17 20:49
interesting finding.
using `2>/dev/null| jq -r '.idsInfo[0].mImage.mData' | hexdump -C` i get this
```
00000000  ef bf bd 07 00 ef bf bd  ef bf bd 7f 00 00 ef bf  |................|
00000010  bd 07 00 ef bf bd ef bf  bd 7f 00 00 ef bf bd ef  |................|
00000020  bf bd 03 ef bf bd ef bf  bd 7f 00 00 ef bf bd ef  |................|
00000030  bf bd 03 ef bf bd ef bf  bd 7f 00 00 43 41 59 41  |............CAYA|
00000040  41 41 44 44 50 6d 48 4c  41 41 41 41 43 58 42 49  |AADDPmHLAAAACXBI|
00000050  57 58 4d 41 41 41 37 45  41 41 41 4f 78 41 47 56  |WXMAAA7EAAAOxAGV|
00000060  4b 77 34 62 41 41 41 66  69 30 6c 45 51 56 52 34  |Kw4bAAAfi0lEQVR4|
```

This "header" looks weird ...

**Comment by sehraf** [comment] 2020-05-17 21:35
This is probably something for @G10h4ck to look into:
This code serializes the image data
```c++
		std::string encodedValue;
		RsBase64::encode(first, second, encodedValue, true, false);
		ctx.mJson.SetString(
		            encodedValue.data(),
		            static_cast<rapidjson::SizeType>(encodedValue.length()) );
```

As far as i understand the documentation [here](https://rapidjson.org/md_doc_tutorial.html#CreateString) the *don't copy* method is used on a stack variable, which is likely the problem here.

Adding the correct allocater seems to fix it:
```
curl -u "test:tset" -d '{ "ids" : ["..."]}' http://127.0.0.1:9094/rsIdentity/getIdentitiesInfo 2>/dev/null| jq -r '.idsInfo[0].mImage.mData' | hexdump -C
00000000  69 56 42 4f 52 77 30 4b  47 67 6f 41 41 41 41 4e  |iVBORw0KGgoAAAAN|
00000010  53 55 68 45 55 67 41 41  41 49 41 41 41 41 43 41  |SUhEUgAAAIAAAACA|
00000020  43 41 59 41 41 41 44 44  50 6d 48 4c 41 41 41 41  |CAYAAADDPmHLAAAA|
```

Using this patch:
```diff
--- a/libretroshare/src/serialiser/rstypeserializer.cc
+++ b/libretroshare/src/serialiser/rstypeserializer.cc
@@ -599,7 +599,7 @@ void RsTypeSerializer::RawMemoryWrapper::serial_process(
                RsBase64::encode(first, second, encodedValue, true, false);
                ctx.mJson.SetString(
                            encodedValue.data(),
-                           static_cast<rapidjson::SizeType>(encodedValue.length()) );
+                           static_cast<rapidjson::SizeType>(encodedValue.length()), ctx.mJson.GetAllocator() );
                break;
        }
        case RsGenericSerializer::FROM_JSON:
```

**Comment by G10h4ck** [comment] 2020-05-17 21:38
Thanks @sehraf your patch seems good to me, if you are so kind to make a PR referencing to this issue I'll be glad to merge it right away

**Comment by b1rdG** [comment] 2020-05-21 15:19
Hi,

I'm on 17b9305ba and after compile it seems that the problem persists:

```
00000000  20 08 00 7c ef bf bd 7f  00 00 20 08 00 7c ef bf  | ..|...... ..|..|
00000010  bd 7f 00 00 10 37 46 7c  ef bf bd 7f 00 00 10 37  |.....7F|.......7|
00000020  46 7c ef bf bd 7f 00 00  43 41 49 41 41 41 42 4d  |F|......CAIAAABM|
00000030  58 50 61 63 41 41 41 41  43 58 42 49 57 58 4d 41  |XPacAAAACXBIWXMA|
00000040  41 42 59 6c 41 41 41 57  4a 51 46 4a 55 69 54 77  |ABYlAAAWJQFJUiTw|
```

I'm not sure if I need to delete some kind of RS cache, or reupload the photo?

**Comment by sehraf** [comment] 2020-05-21 15:37
cannot reproduce it locally. Tried a few IDs and they all worked. You can always try a clean recompile.

E.g. here is Cyrils cat: `curl -u "test:tset" -d '{ "ids" : ["4c1abf201be5a8fe94f6896f6adc9b11"]}' http://127.0.0.1:9092/rsIdentity/getIdentitiesInfo 2>/dev/null| jq -r '.idsInfo[0].mImage.mData' | base64 -d | display`

other ID:
```
curl -u "test:tset" -d '{ "ids" : ["..."]}' http://127.0.0.1:9092/rsIdentity/getIdentitiesInfo 2>/dev/null| | jq -r '.idsInfo[0].mImage.mData' | base64 -d | hexdump -C | head
00000000  89 50 4e 47 0d 0a 1a 0a  00 00 00 0d 49 48 44 52  |.PNG........IHDR|
00000010  00 00 00 80 00 00 00 80  08 06 00 00 00 c3 3e 61  |..............>a|
00000020  cb 00 00 00 09 70 48 59  73 00 00 0e c4 00 00 0e  |.....pHYs.......|
00000030  c4 01 95 2b 0e 1b 00 00  1f 8b 49 44 41 54 78 9c  |...+......IDATx.|
```

**Comment by G10h4ck** [comment] 2020-05-21 15:44
try blazing away the build directory with `rm -rf`

**Comment by b1rdG** [comment] 2020-05-21 15:48
Well now it works, I changed the image, rebuilt and it works. Now It return a strange thing but i'm not sure that is important:

With curl, the image ends:

```
Tz/z6U9mmSEMIFY9qQjSKUfdn7fvp8/ep+vRw4uP/YHp01odUwPAoiRNG55Y6XrrBDYN9TpmAPD/AWrKQ+Gak2U1AAAAAElFTkSuQmCC\u0000\u0000"
```

The last two chars are `\u0000\u0000`, If I hexdump it:

```
000081a0  36 58 72 72 42 44 59 4e  39 54 70 6d 41 50 44 2f  |6XrrBDYN9TpmAPD/|
000081b0  41 57 72 4b 51 2b 47 61  6b 32 55 31 41 41 41 41  |AWrKQ+Gak2U1AAAA|
000081c0  41 45 6c 46 54 6b 53 75  51 6d 43 43 00 00 0a     |AElFTkSuQmCC...|
000081cf
```

I'm not sure if is something strange. Anyway I can rebuild the image on a online Base64 to image service.

**Comment by G10h4ck** [comment] 2020-05-21 15:50
That `\u0000\u0000` at the end is quite suspicious... but i could not reproduce it

**Comment by b1rdG** [comment] 2020-05-21 16:08
Yes, I'm looking for Ids without avatar and they return things like:

```
"mImage": {
                "mData": "\u0000\u0000"
            },
```

```
00000000  00 00 0a                                          |...|
00000003
```

**Comment by b1rdG** [comment] 2020-05-21 16:17
With this two ending characters I can't use the images on the Flutter app.

BTW, a quick dirty patch: 

```dart
this._avatar = avatar.substring(0, avatar.length - 2);
```

**Comment by G10h4ck** [comment] 2020-05-21 16:19
but that patch will break images which don't have the last 0 bytes

**Comment by G10h4ck** [comment] 2020-05-21 16:20
try this patch  https://github.com/RetroShare/RetroShare/pull/1959

**Comment by b1rdG** [comment] 2020-05-21 16:39
This patch return an empty image string without avatar, but stills returning an ending `\u0000\u0000` when is defined.

**Comment by G10h4ck** [comment] 2020-05-22 10:08
can you pass to me an image which cause that so I can reproduce it on my station? I think it is due to some error in padding, so i need an image which need padding to reproduce it

**Comment by b1rdG** [comment] 2020-05-22 15:32
Well, is just my profile image:

![external-content duckduckgo com](https://user-images.githubusercontent.com/61605133/82683889-486afd80-9c41-11ea-8a2a-b222ebaad8af.jpeg)

**Comment by sehraf** [comment] 2020-05-22 15:36
can reproduce it with your image/id
```
curl -u "test:tset" -d '{ "ids" : ["33...d1"]}' http://127.0.0.1:9092/rsIdentity/getIdentitiesInfo 2>/dev/null| jq -r '.idsInfo[0].mImage.mData' | hexdump -C | tail  
000070b0  44 41 41 2b 6b 6d 52 46  4b 66 72 62 4f 55 59 63  |DAA+kmRFKfrbOUYc|
000070c0  59 35 4d 57 51 68 41 56  55 53 46 76 79 63 62 67  |Y5MWQhAVUSFvycbg|
000070d0  34 66 37 63 6b 6e 69 70  79 51 41 69 42 7a 59 7a  |4f7cknipyQAiBzYz|
000070e0  56 38 70 43 68 43 65 58  2b 34 38 2f 2f 4f 34 6e  |V8pChCeX+48//O4n|
000070f0  50 2f 37 4f 39 39 35 2f  6d 31 32 31 34 78 77 36  |P/7O995/m1214xw6|
00007100  67 30 56 6a 5a 64 57 64  36 44 42 63 74 33 39 62  |g0VjZdWd6DBct39b|
00007110  53 75 35 2f 42 36 79 5a  31 37 54 68 51 7a 39 56  |Su5/B6yZ17ThQz9V|
00007120  41 41 41 41 41 45 6c 46  54 6b 53 75 51 6d 43 43  |AAAAAElFTkSuQmCC|
00007130  00 00 0a                                          |...|
00007133
```

The 0a =  \n is suspicious, too

**Comment by b1rdG** [comment] 2020-05-28 15:45
Well, BTW I created a simple ugly patch to support avatars on flutter app meanwhile this is not solved. https://gitlab.com/b1rdG/retroshare-android-flutter-app/-/commit/942e99f47025f668f017cd2f7af82a4755456d3c

**Comment by G10h4ck** [comment] 2020-05-28 16:00
Please try again https://github.com/RetroShare/RetroShare/pull/1959  should be fixed with latest commit

**Comment by sehraf** [comment] 2020-05-28 16:20
I don't get it:
```c++
		RsDbg() << __PRETTY_FUNCTION__ << " size=" << second << " data[0]=" << std::hex << (int)first[0] << " data[-1]=" << std::hex << (int)first[second-1] << std::endl;

		std::string encodedValue;
		RsBase64::encode(first, second, encodedValue, true, false);

		RsDbg() << __PRETTY_FUNCTION__ << " size=" << encodedValue.length() << " encodedValue[0]=" << std::hex << (int)encodedValue[0] << " encodedValue[-1]=" << std::hex << (int)encodedValue[encodedValue.length()-1] << std::endl;
```
results in this
```
D 1590681409.437 virtual void RsTypeSerializer::RawMemoryWrapper::serial_process(RsGenericSerializer::SerializeJob, RsGenericSerializer::SerializeContext&) size=21732 data[0]=89 data[-1]=82
D 1590681409.437 virtual void RsTypeSerializer::RawMemoryWrapper::serial_process(RsGenericSerializer::SerializeJob, RsGenericSerializer::SerializeContext&) size=7132 encodedValue[0]=69 encodedValue[-1]=0
```
So the \0 seems to come from the base64 encoding.

The size makes no sense, the first char fits. Any ideas @G10h4ck ?
When using `| base64 -d | hexdump -C` the last char fits, too


EDIT: just saw you post, i was looking at the same stackoverflow post :D

**Comment by b1rdG** [comment] 2020-05-28 16:24
It work for me, the base64 string has no strange chars. Neither at:

* Beginning of base64 string
* End of base64 string with or without padding
* Empty image

**Comment by sehraf** [comment] 2020-05-28 16:30
can confirm, too,  that the problem is fixed

**Comment by G10h4ck** [comment] 2020-05-28 16:31
Thanks for testing!

**Comment by G10h4ck** [comment] 2020-05-28 16:45
Fixed merging https://github.com/RetroShare/RetroShare/pull/1959

**Closed as completed by G10h4ck** 2020-05-28 16:45 UTC

**Comment by b1rdG** [comment] 2020-05-29 13:57
Thanks!
